-- ============================================================
-- AVIA Homes — Catalogue Tables (Colours, Specs, Schemes, Ranges)
-- Run this in Supabase SQL Editor AFTER supabase_schema.sql
-- and supabase_content_tables.sql
-- ============================================================

-- 1. Colour Categories
CREATE TABLE IF NOT EXISTS colour_categories (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    icon TEXT NOT NULL,
    section TEXT NOT NULL CHECK (section IN ('exterior', 'interior')),
    note TEXT,
    image_url TEXT,
    sort_order INT NOT NULL DEFAULT 0,
    options JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Spec Categories
CREATE TABLE IF NOT EXISTS spec_categories (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    icon TEXT NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    items JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 3. Spec Range Tiers
CREATE TABLE IF NOT EXISTS spec_range_tiers (
    tier TEXT PRIMARY KEY,
    hero_image_url TEXT NOT NULL,
    summary TEXT NOT NULL,
    highlights JSONB NOT NULL DEFAULT '[]'::jsonb,
    room_images JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 4. HomeFast Schemes
CREATE TABLE IF NOT EXISTS homefast_schemes (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    subtitle TEXT NOT NULL,
    preview_colors JSONB NOT NULL DEFAULT '[]'::jsonb,
    selections JSONB NOT NULL DEFAULT '{}'::jsonb,
    room_images JSONB NOT NULL DEFAULT '[]'::jsonb,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 5. Spec-to-Colour Mapping
CREATE TABLE IF NOT EXISTS spec_to_colour_mapping (
    spec_item_id TEXT PRIMARY KEY,
    colour_category_ids TEXT[] NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 6. Spec Item Images
CREATE TABLE IF NOT EXISTS spec_item_images (
    spec_item_id TEXT PRIMARY KEY,
    base_image_url TEXT,
    tier_images JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- ============================================================
-- Row Level Security — public read, authenticated write
-- ============================================================

ALTER TABLE colour_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE spec_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE spec_range_tiers ENABLE ROW LEVEL SECURITY;
ALTER TABLE homefast_schemes ENABLE ROW LEVEL SECURITY;
ALTER TABLE spec_to_colour_mapping ENABLE ROW LEVEL SECURITY;
ALTER TABLE spec_item_images ENABLE ROW LEVEL SECURITY;

-- Public read
CREATE POLICY "Public read colour_categories" ON colour_categories FOR SELECT USING (true);
CREATE POLICY "Public read spec_categories" ON spec_categories FOR SELECT USING (true);
CREATE POLICY "Public read spec_range_tiers" ON spec_range_tiers FOR SELECT USING (true);
CREATE POLICY "Public read homefast_schemes" ON homefast_schemes FOR SELECT USING (true);
CREATE POLICY "Public read spec_to_colour_mapping" ON spec_to_colour_mapping FOR SELECT USING (true);
CREATE POLICY "Public read spec_item_images" ON spec_item_images FOR SELECT USING (true);

-- Authenticated write (for admin management)
CREATE POLICY "Auth write colour_categories" ON colour_categories FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Auth write spec_categories" ON spec_categories FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Auth write spec_range_tiers" ON spec_range_tiers FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Auth write homefast_schemes" ON homefast_schemes FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Auth write spec_to_colour_mapping" ON spec_to_colour_mapping FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Auth write spec_item_images" ON spec_item_images FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

-- ============================================================
-- SEED DATA — Colour Categories
-- ============================================================

-- EXTERIOR
INSERT INTO colour_categories (id, name, icon, section, note, image_url, sort_order, options) VALUES
('roof', 'Roof', 'house.fill', 'exterior', 'Colorbond steel roofing', 'https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/334c00ed-5e46-4811-b980-e82eeb55f8c7.png', 1,
 '[{"id":"r1","name":"Surfmist","hex_color":"E4E2D5","brand":"Colorbond"},{"id":"r2","name":"Dover White","hex_color":"F9FBF1","brand":"Colorbond"},{"id":"r3","name":"Southerly","hex_color":"D2D1CB","brand":"Colorbond"},{"id":"r4","name":"Evening Haze","hex_color":"C5C2AA","brand":"Colorbond"},{"id":"r5","name":"Shale Grey","hex_color":"BDBFBA","brand":"Colorbond"},{"id":"r6","name":"Windspray","hex_color":"888B8A","brand":"Colorbond"},{"id":"r7","name":"Dune","hex_color":"B1ADA3","brand":"Colorbond"},{"id":"r8","name":"Bluegum","hex_color":"969799","brand":"Colorbond"},{"id":"r9","name":"Paperbark","hex_color":"CABFA4","brand":"Colorbond"}]'),
('fascia', 'Fascia & Gutters', 'rectangle.topthird.inset.filled', 'exterior', NULL, 'https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/40825f3c-00d2-4493-a990-99e90fbaef85.png', 2,
 '[{"id":"f1","name":"Dover White","hex_color":"F9FBF1","brand":"Colorbond"},{"id":"f2","name":"Southerly","hex_color":"D2D1CB","brand":"Colorbond"},{"id":"f3","name":"Shale Grey","hex_color":"BDBFBA","brand":"Colorbond"},{"id":"f4","name":"Dune","hex_color":"B1ADA3","brand":"Colorbond"},{"id":"f5","name":"Bluegum","hex_color":"969799","brand":"Colorbond"},{"id":"f6","name":"Paperbark","hex_color":"CABFA4","brand":"Colorbond"},{"id":"f7","name":"Evening Haze","hex_color":"C5C2AA","brand":"Colorbond"},{"id":"f8","name":"Windspray","hex_color":"888B8A","brand":"Colorbond"},{"id":"f9","name":"Surfmist","hex_color":"E4E2D5","brand":"Colorbond"}]'),
('windows', 'Windows & Doors', 'window.vertical.open', 'exterior', 'Aluminium window & sliding door frames', 'https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/2c31d2c6-ff2f-4372-9747-cad59e8dc93e.png', 3,
 '[{"id":"w1","name":"Surfmist","hex_color":"E4E2D5"},{"id":"w2","name":"Monument","hex_color":"2D2C2C"},{"id":"w3","name":"Black","hex_color":"1A1A1A"},{"id":"w4","name":"Paperbark","hex_color":"CABFA4"},{"id":"w5","name":"Woodland Grey","hex_color":"4C4F48"},{"id":"w6","name":"Windspray","hex_color":"888B8A"}]'),
('garage', 'Garage Door', 'door.garage.closed', 'exterior', NULL, 'https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/b70a12a1-d0ae-4ea7-a3e9-1e71f5cd069b.png', 4,
 '[{"id":"g1","name":"Surfmist","hex_color":"E4E2D5","brand":"Colorbond"},{"id":"g2","name":"Dover White","hex_color":"F9FBF1","brand":"Colorbond"},{"id":"g3","name":"Shale Grey","hex_color":"BDBFBA","brand":"Colorbond"},{"id":"g4","name":"Dune","hex_color":"B1ADA3","brand":"Colorbond"},{"id":"g5","name":"Windspray","hex_color":"888B8A","brand":"Colorbond"},{"id":"g6","name":"Monument","hex_color":"2D2C2C","brand":"Colorbond"},{"id":"g7","name":"Woodland Grey","hex_color":"4C4F48","brand":"Colorbond"},{"id":"g8","name":"Paperbark","hex_color":"CABFA4","brand":"Colorbond"},{"id":"g9","name":"Evening Haze","hex_color":"C5C2AA","brand":"Colorbond"}]'),
('render', 'Render', 'paintbrush.fill', 'exterior', 'Hardie fine texture render', 'colour_render', 5,
 '[{"id":"re1","name":"Surfmist","hex_color":"E4E2D5","brand":"Dulux"},{"id":"re2","name":"Dover White","hex_color":"F9FBF1","brand":"Dulux"},{"id":"re3","name":"Southerly","hex_color":"D2D1CB","brand":"Dulux"},{"id":"re4","name":"Shale Grey","hex_color":"BDBFBA","brand":"Dulux"},{"id":"re5","name":"Dune","hex_color":"B1ADA3","brand":"Dulux"},{"id":"re6","name":"Evening Haze","hex_color":"C5C2AA","brand":"Dulux"},{"id":"re7","name":"Paperbark","hex_color":"CABFA4","brand":"Dulux"},{"id":"re8","name":"Windspray","hex_color":"888B8A","brand":"Dulux"}]'),
('cladding', 'Secondary Cladding', 'square.stack.3d.up.fill', 'exterior', 'Scyon or Colorbond cladding', 'https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/7561ad2f-341f-4c28-a916-be13ebbf680e.png', 6,
 '[{"id":"cl1","name":"Surfmist","hex_color":"E4E2D5","brand":"Colorbond"},{"id":"cl2","name":"Monument","hex_color":"2D2C2C","brand":"Colorbond"},{"id":"cl3","name":"Shale Grey","hex_color":"BDBFBA","brand":"Colorbond"},{"id":"cl4","name":"Dune","hex_color":"B1ADA3","brand":"Colorbond"},{"id":"cl5","name":"Basalt","hex_color":"4A4946","brand":"Colorbond"},{"id":"cl6","name":"Woodland Grey","hex_color":"4C4F48","brand":"Colorbond"},{"id":"cl7","name":"Windspray","hex_color":"888B8A","brand":"Colorbond"},{"id":"cl8","name":"Evening Haze","hex_color":"C5C2AA","brand":"Colorbond"}]'),
('bricks', 'Bricks', 'rectangle.grid.2x2.fill', 'exterior', NULL, 'colour_bricks', 7,
 '[{"id":"b1","name":"Graphite","hex_color":"3A3A3A"},{"id":"b2","name":"Charcoal","hex_color":"4E4E4E"},{"id":"b3","name":"Silver","hex_color":"A8A8A8"},{"id":"b4","name":"Sand","hex_color":"C4B89C"},{"id":"b5","name":"Mocha","hex_color":"8B7355"},{"id":"b6","name":"Hazelnut","hex_color":"9C8468"},{"id":"b7","name":"Alabaster","hex_color":"D8D0C4"},{"id":"b8","name":"Limestone","hex_color":"C8C0B0"}]'),
('frontdoor', 'Front Door', 'door.left.hand.closed', 'exterior', 'Corinthian 1200mm wide front door', 'https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/e0f43702-9412-4d39-94fe-10dca04f98ab.png', 8,
 '[{"id":"fd1","name":"Surfmist","hex_color":"E4E2D5","brand":"Dulux"},{"id":"fd2","name":"Monument","hex_color":"2D2C2C","brand":"Dulux"},{"id":"fd3","name":"Dune","hex_color":"B1ADA3","brand":"Dulux"},{"id":"fd4","name":"Shale Grey","hex_color":"BDBFBA","brand":"Dulux"},{"id":"fd5","name":"Woodland Grey","hex_color":"4C4F48","brand":"Dulux"},{"id":"fd6","name":"Windspray","hex_color":"888B8A","brand":"Dulux"},{"id":"fd7","name":"Basalt","hex_color":"4A4946","brand":"Dulux"},{"id":"fd8","name":"Black","hex_color":"1A1A1A","brand":"Dulux"}]'),
('timberposts', 'Timber Posts', 'rectangle.portrait.fill', 'exterior', NULL, 'colour_timber_posts', 9,
 '[{"id":"tp1","name":"Surfmist","hex_color":"E4E2D5","brand":"Dulux"},{"id":"tp2","name":"Monument","hex_color":"2D2C2C","brand":"Dulux"},{"id":"tp3","name":"Shale Grey","hex_color":"BDBFBA","brand":"Dulux"},{"id":"tp4","name":"Dune","hex_color":"B1ADA3","brand":"Dulux"},{"id":"tp5","name":"Paperbark","hex_color":"CABFA4","brand":"Dulux"},{"id":"tp6","name":"Woodland Grey","hex_color":"4C4F48","brand":"Dulux"}]'),
('alfrescotiles', 'Alfresco Tiles', 'squareshape.split.3x3', 'exterior', '300x300mm porcelain tiles', 'https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/f6797126-b0d6-4da9-a083-b6164d3e8c66.png', 10,
 '[{"id":"at1","name":"Concrete Grey","hex_color":"A8A4A0"},{"id":"at2","name":"Charcoal","hex_color":"4E4E4E"},{"id":"at3","name":"Sandstone","hex_color":"C4B89C"},{"id":"at4","name":"Ivory","hex_color":"E8E0D0"},{"id":"at5","name":"Slate","hex_color":"6B6B6B"},{"id":"at6","name":"Taupe","hex_color":"B0A898"}]'),
('aggregate', 'Exposed Aggregate', 'circle.hexagongrid.fill', 'exterior', 'Exposed aggregate driveway & paths', 'https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/9e5ce3c7-7a24-42ea-a992-67b9ecaa9863.png', 11,
 '[{"id":"ea1","name":"Cream","hex_color":"D8D0B8"},{"id":"ea2","name":"Mocha","hex_color":"8B7355"},{"id":"ea3","name":"Charcoal","hex_color":"4E4E4E"},{"id":"ea4","name":"Sandstone","hex_color":"C4B89C"},{"id":"ea5","name":"Platinum","hex_color":"A8A8A8"},{"id":"ea6","name":"Salt & Pepper","hex_color":"908C84"}]')
ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, icon=EXCLUDED.icon, section=EXCLUDED.section, note=EXCLUDED.note, image_url=EXCLUDED.image_url, sort_order=EXCLUDED.sort_order, options=EXCLUDED.options, updated_at=now();

-- INTERIOR
INSERT INTO colour_categories (id, name, icon, section, note, image_url, sort_order, options) VALUES
('paint', 'Paint – Walls, Doors & Trim', 'paintbrush.pointed.fill', 'interior', 'Low sheen finish to walls, semi-gloss to trims & doors', 'https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/caefb1ad-7576-4d28-aae2-7c071c0299bd.png', 20,
 '[{"id":"p1","name":"Vivid White","hex_color":"F7F7F2","brand":"Dulux"},{"id":"p2","name":"Lexicon Quarter","hex_color":"F2F2EA","brand":"Dulux"},{"id":"p3","name":"Lexicon Half","hex_color":"EEEEE6","brand":"Dulux"},{"id":"p4","name":"Natural White","hex_color":"E8E3D8","brand":"Dulux"},{"id":"p5","name":"Warm White","hex_color":"F0E8DA","brand":"Dulux"},{"id":"p6","name":"Antique White USA","hex_color":"F0EADC","brand":"Dulux"}]'),
('flooring', 'Main Flooring', 'square.grid.3x3.fill', 'interior', 'Hybrid floating floor throughout living areas', 'https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/fa4b70a7-2b9f-4e9a-b649-f38b88e768f2.png', 21,
 '[{"id":"fl1","name":"Coastal Oak","hex_color":"B8A88A"},{"id":"fl2","name":"Spotted Gum","hex_color":"8B7355"},{"id":"fl3","name":"Blackbutt","hex_color":"C4AA82"},{"id":"fl4","name":"Grey Wash Oak","hex_color":"A09A90"},{"id":"fl5","name":"Classic Oak","hex_color":"B0956E"},{"id":"fl6","name":"Smoked Oak","hex_color":"7A6A56"},{"id":"fl7","name":"Brushed Elm","hex_color":"9C8A72"},{"id":"fl8","name":"Jarrah","hex_color":"6B3A2A","is_upgrade":true}]'),
('carpet', 'Carpet', 'rectangle.fill', 'interior', 'Solution-dyed nylon carpet to bedrooms', 'https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/bb70cdd0-bc57-44e4-a733-c82249f71e0b.png', 22,
 '[{"id":"c1","name":"Cloud","hex_color":"D4D0CA"},{"id":"c2","name":"Sandstone","hex_color":"C4B89C"},{"id":"c3","name":"Silver","hex_color":"B8B4AE"},{"id":"c4","name":"Steel","hex_color":"8E8A84"},{"id":"c5","name":"Ash","hex_color":"A8A4A0"},{"id":"c6","name":"Suede","hex_color":"B0A08C"},{"id":"c7","name":"Pebble","hex_color":"C0B8AC"},{"id":"c8","name":"Truffle","hex_color":"7A7068"}]'),
('blinds', 'Blinds', 'blinds.vertical.closed', 'interior', 'Roller blinds throughout', 'https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/c87335e4-5574-4a0a-8da4-3a923a4fa4fa.png', 23,
 '[{"id":"bl1","name":"White","hex_color":"F5F5F0"},{"id":"bl2","name":"Ivory","hex_color":"E8E0D0"},{"id":"bl3","name":"Linen","hex_color":"D8D0C0"},{"id":"bl4","name":"Stone","hex_color":"B8B0A4"},{"id":"bl5","name":"Charcoal","hex_color":"4E4E4E"},{"id":"bl6","name":"Pewter","hex_color":"8A8682"}]'),
('benchtops', 'Stone Benchtops', 'rectangle.split.3x1.fill', 'interior', '20mm stone benchtops to kitchen, bathroom & ensuite', 'https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/46e4d506-49f6-4e02-86c5-f1bf8796d80e.png', 24,
 '[{"id":"st1","name":"Calacatta White","hex_color":"F0EDE8"},{"id":"st2","name":"Statuario","hex_color":"E8E4DE"},{"id":"st3","name":"Concrete Grey","hex_color":"A8A4A0"},{"id":"st4","name":"Empira White","hex_color":"EAE6E0"},{"id":"st5","name":"Noble Grey","hex_color":"B0ACA6"},{"id":"st6","name":"Alpine Mist","hex_color":"D8D4CC"},{"id":"st7","name":"Midnight","hex_color":"2A2A2A","is_upgrade":true}]'),
('splashback', 'Kitchen Splashback', 'rectangle.stack.fill', 'interior', '600x300mm ceramic tiles', 'https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/d66a2cc1-dd27-42b6-8207-87fc014af408.png', 25,
 '[{"id":"sp1","name":"White Gloss","hex_color":"F5F5F0"},{"id":"sp2","name":"White Matt","hex_color":"F0F0EA"},{"id":"sp3","name":"Marble Look","hex_color":"E8E4DE"},{"id":"sp4","name":"Grey Stone","hex_color":"B0ACA6"},{"id":"sp5","name":"Warm Beige","hex_color":"D4C8B4"},{"id":"sp6","name":"Sage Green","hex_color":"A8B4A0","is_upgrade":true}]'),
('cabinetry', 'Kitchen Cabinetry', 'cabinet.fill', 'interior', 'Polytec doors & panels', 'https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/4bb89f20-56b3-4bad-9d89-5480cbba9730.png', 26,
 '[{"id":"k1","name":"Classic White","hex_color":"F5F5F0"},{"id":"k2","name":"Coastal Grey","hex_color":"B0ACA6"},{"id":"k3","name":"Natural Oak","hex_color":"C4AA82"},{"id":"k4","name":"Ash Grey","hex_color":"A09A90"},{"id":"k5","name":"Stone","hex_color":"B8B0A4"},{"id":"k6","name":"Charcoal","hex_color":"3A3A3A","is_upgrade":true}]'),
('pendants', 'Pendant Lights', 'light.cylindrical.ceiling.fill', 'interior', 'Kitchen pendant lights', 'https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/f0078008-fb84-4cae-89bf-03bf545ab9ae.png', 27,
 '[{"id":"pl1","name":"White","hex_color":"F5F5F0"},{"id":"pl2","name":"Matte Black","hex_color":"1A1A1A"},{"id":"pl3","name":"Brushed Nickel","hex_color":"B0A898"},{"id":"pl4","name":"Brushed Chrome","hex_color":"C8C8C8"}]'),
('tapware', 'Tapware', 'drop.fill', 'interior', 'Kitchen, bathroom & ensuite mixers', 'https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/43f4d48a-083b-4151-821f-4ae3edd32556.png', 28,
 '[{"id":"t1","name":"Chrome","hex_color":"C8C8C8"},{"id":"t2","name":"Brushed Nickel","hex_color":"B0A898"},{"id":"t3","name":"Matte Black","hex_color":"1A1A1A"},{"id":"t4","name":"Brushed Gold","hex_color":"C4A872","is_upgrade":true},{"id":"t5","name":"Gunmetal","hex_color":"4A4A4A","is_upgrade":true}]'),
('bathtiles', 'Bathroom Tiles', 'square.grid.2x2.fill', 'interior', 'Wall & floor tiles to bathroom, ensuite & WC', 'https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/e47e1af2-689c-45b3-a015-1ce13d7e72df.png', 29,
 '[{"id":"bt1","name":"White Matt","hex_color":"F0F0EA"},{"id":"bt2","name":"White Gloss","hex_color":"F5F5F0"},{"id":"bt3","name":"Grey Matt","hex_color":"B0ACA6"},{"id":"bt4","name":"Warm Beige","hex_color":"D4C8B4"},{"id":"bt5","name":"Ivory","hex_color":"E8E0D0"},{"id":"bt6","name":"Terrazzo Look","hex_color":"D8D4CC","is_upgrade":true}]'),
('vanity', 'Vanity', 'sink.fill', 'interior', 'Wall-hung vanity units to bathroom & ensuite', 'https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/93c2594a-5968-45a9-8913-0ad3a4888763.png', 30,
 '[{"id":"v1","name":"Classic White","hex_color":"F5F5F0"},{"id":"v2","name":"Natural Oak","hex_color":"C4AA82"},{"id":"v3","name":"Coastal Grey","hex_color":"B0ACA6"},{"id":"v4","name":"Stone","hex_color":"B8B0A4"},{"id":"v5","name":"Dark Elm","hex_color":"5A4A38","is_upgrade":true}]'),
('wardrobes', 'Wardrobe Shelving', 'square.split.2x2.fill', 'interior', 'Adjustable wardrobe shelving system', 'colour_wardrobes', 31,
 '[{"id":"ws1","name":"Classic White","hex_color":"F5F5F0"},{"id":"ws2","name":"Natural Oak","hex_color":"C4AA82"},{"id":"ws3","name":"Grey","hex_color":"B0ACA6"}]'),
('doorhandles', 'Internal Door Handles', 'lock.fill', 'interior', 'Lemaar Metz passage, privacy & dummy sets', 'https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/6433305a-0678-41e3-bb2f-674acf30f38d.png', 32,
 '[{"id":"dh1","name":"Satin Chrome","hex_color":"C0C0C0"},{"id":"dh2","name":"Matte Black","hex_color":"1A1A1A"},{"id":"dh3","name":"Brushed Nickel","hex_color":"B0A898"}]'),
('bathaccessories', 'Bathroom Accessories', 'shower.fill', 'interior', 'Towel rail, toilet roll holder & robe hook', 'https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/0175ddfa-4190-45a1-ba20-75740fae68b0.png', 33,
 '[{"id":"ba1","name":"Chrome","hex_color":"C8C8C8"},{"id":"ba2","name":"Matte Black","hex_color":"1A1A1A"},{"id":"ba3","name":"Brushed Nickel","hex_color":"B0A898"}]'),
('showerscreens', 'Shower Screens', 'rectangle.portrait.fill', 'interior', 'Semi-frameless shower screens', 'https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/50cb415d-3749-47e9-9356-000f6339681d.png', 34,
 '[{"id":"ss1","name":"Silver / Chrome","hex_color":"C0C0C0"},{"id":"ss2","name":"Matte Black","hex_color":"1A1A1A"},{"id":"ss3","name":"Brushed Nickel","hex_color":"B0A898"}]'),
('mirrors', 'Mirrors', 'rectangle.fill', 'interior', 'Vanity mirrors to bathroom & ensuite', 'https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/d8d1ce6d-8dec-4843-ae63-be0080b7e78d.png', 35,
 '[{"id":"mi1","name":"Frameless Polished Edge","hex_color":"D8E0E8"},{"id":"mi2","name":"Matte Black Frame","hex_color":"1A1A1A"},{"id":"mi3","name":"Brushed Nickel Frame","hex_color":"B0A898"}]'),
('powerpoints', 'Powerpoints & Switches', 'poweroutlet.type.i.fill', 'interior', 'Clipsal switches & power points', 'https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/aa4f5413-40de-4206-9b82-f85323aa5f31.png', 36,
 '[{"id":"pp1","name":"Gloss White","hex_color":"F5F5F0"},{"id":"pp2","name":"Matt White","hex_color":"EEEEEA"},{"id":"pp3","name":"Black","hex_color":"1A1A1A","is_upgrade":true}]'),
('laundrytub', 'Laundry Tub', 'spigot.fill', 'interior', '45L laundry tub with cabinet', 'colour_laundry_tub', 37,
 '[{"id":"lt1","name":"Classic White Cabinet","hex_color":"F5F5F0"},{"id":"lt2","name":"Natural Oak Cabinet","hex_color":"C4AA82"},{"id":"lt3","name":"Stone Grey Cabinet","hex_color":"B0ACA6"}]')
ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, icon=EXCLUDED.icon, section=EXCLUDED.section, note=EXCLUDED.note, image_url=EXCLUDED.image_url, sort_order=EXCLUDED.sort_order, options=EXCLUDED.options, updated_at=now();

-- ============================================================
-- SEED DATA — Spec Categories
-- ============================================================

INSERT INTO spec_categories (id, name, icon, sort_order, items) VALUES
('structure', 'Structure & Ceiling', 'building.2.fill', 1,
 '[{"id":"ceiling_height","name":"Ceiling Height","volos_description":"2,440mm internal ceiling height","messina_description":"2,590mm internal ceiling height","portobello_description":"2,740mm internal ceiling height","is_upgradeable":true},{"id":"concrete_slab","name":"Concrete Slab","volos_description":"Engineer designed slab to suit soil conditions","messina_description":"Engineer designed slab to suit soil conditions","portobello_description":"Engineer designed slab to suit soil conditions","is_upgradeable":false},{"id":"frame_trusses","name":"Frame & Trusses","volos_description":"Termite-resistant H2F blue treated pine timber","messina_description":"Termite-resistant H2F blue treated pine timber","portobello_description":"Termite-resistant H2F blue treated pine timber","is_upgradeable":false},{"id":"insulation","name":"Insulation Batts","volos_description":"R 3.5 ceiling batts, R 2.0 wall batts","messina_description":"R 3.5 ceiling batts, R 2.0 wall batts","portobello_description":"R 3.5 ceiling batts, R 2.0 wall batts","is_upgradeable":false}]'),
('exterior', 'External Finishes', 'house.fill', 2,
 '[{"id":"facade","name":"Facade Finish","volos_description":"Face brick from standard range with off-white mortar, ironed profile","messina_description":"Face brick from standard range with off-white mortar, ironed profile","portobello_description":"Face brick from standard range with off-white mortar, ironed profile","is_upgradeable":true},{"id":"cladding","name":"Lightweight Cladding","volos_description":"Painted finish as per plan","messina_description":"Painted finish as per plan","portobello_description":"Painted finish as per plan","is_upgradeable":false},{"id":"roof","name":"Roof","volos_description":"COLORBOND® corrugated steel roofing with standard colour range","messina_description":"COLORBOND® corrugated steel roofing with standard colour range","portobello_description":"COLORBOND® corrugated steel roofing with full colour range","is_upgradeable":true},{"id":"fascia_gutters","name":"Fascia & Gutters","volos_description":"COLORBOND® fascia, gutters & PVC downpipes","messina_description":"COLORBOND® fascia, gutters & PVC downpipes","portobello_description":"COLORBOND® fascia, gutters & PVC downpipes","is_upgradeable":false},{"id":"driveway","name":"Driveway","volos_description":"Standard concrete driveway","messina_description":"Broom finish concrete driveway","portobello_description":"Exposed aggregate concrete driveway","is_upgradeable":true}]'),
('windows_doors', 'Windows & Doors', 'door.left.hand.open', 3,
 '[{"id":"windows","name":"Windows","volos_description":"Aluminium windows with keyed locks","messina_description":"Aluminium windows with keyed locks & Low-E glass","portobello_description":"Powder-coated aluminium windows with keyed locks & Low-E glass","is_upgradeable":true},{"id":"ext_doors","name":"External Doors","volos_description":"2,100mm high external doors","messina_description":"2,100mm high external doors","portobello_description":"2,340mm high external doors","is_upgradeable":true},{"id":"front_entry","name":"Front Entry Door","volos_description":"Standard hinged front entry door","messina_description":"Corinthian Blonde Oak front entry with digital touchpad lock","portobello_description":"1,200mm wide Corinthian Blonde Oak entry with digital touchpad lock","is_upgradeable":true},{"id":"security_screens","name":"Security Screens","volos_description":"Diamond grille with fibreglass mesh fly screens","messina_description":"Diamond grille with fibreglass mesh fly screens","portobello_description":"Diamond grille with fibreglass mesh fly screens on all openings","is_upgradeable":false},{"id":"garage_door","name":"Garage Door","volos_description":"Panel lift garage door","messina_description":"Panel lift garage door with 2 x remotes","portobello_description":"Panel lift garage door with 2 x remotes","is_upgradeable":true}]'),
('kitchen', 'Kitchen', 'fork.knife', 4,
 '[{"id":"benchtop","name":"Benchtop","volos_description":"Laminate benchtop from standard range","messina_description":"20mm stone benchtop from standard range","portobello_description":"20mm premium stone benchtop from extended range","is_upgradeable":true},{"id":"cabinetry","name":"Cabinetry","volos_description":"Standard flat panel cabinetry in white","messina_description":"Two-tone cabinetry with soft-close drawers & doors","portobello_description":"Premium two-tone cabinetry with soft-close, pot drawers & pantry internals","is_upgradeable":true},{"id":"splashback","name":"Splashback","volos_description":"Standard tiled splashback","messina_description":"600mm tiled splashback from standard range","portobello_description":"Full-height tiled splashback from premium range","is_upgradeable":true},{"id":"sink","name":"Sink","volos_description":"Single bowl stainless steel sink","messina_description":"1 & 3/4 bowl stainless steel undermount sink","portobello_description":"Double bowl stainless steel undermount sink","is_upgradeable":true},{"id":"tapware","name":"Tapware","volos_description":"Chrome mixer tap","messina_description":"Chrome gooseneck mixer tap","portobello_description":"Matte black gooseneck mixer tap","is_upgradeable":true},{"id":"appliances","name":"Appliances","volos_description":"600mm oven, ceramic cooktop & rangehood","messina_description":"900mm oven, 5-burner gas cooktop & rangehood","portobello_description":"900mm pyrolytic oven, induction cooktop, integrated rangehood & dishwasher","is_upgradeable":true}]'),
('bathroom', 'Bathroom & Ensuite', 'shower.fill', 5,
 '[{"id":"floor_tiles","name":"Floor Tiles","volos_description":"Standard ceramic floor tiles","messina_description":"300x600mm porcelain floor tiles from standard range","portobello_description":"600x600mm porcelain floor tiles from premium range","is_upgradeable":true},{"id":"wall_tiles","name":"Wall Tiles","volos_description":"Standard ceramic wall tiles to 1,200mm","messina_description":"300x600mm porcelain wall tiles to 1,800mm","portobello_description":"300x600mm porcelain wall tiles floor to ceiling","is_upgradeable":true},{"id":"vanity","name":"Vanity","volos_description":"Standard 750mm vanity with ceramic top","messina_description":"900mm wall-hung vanity with stone top","portobello_description":"1,200mm wall-hung double vanity with stone top","is_upgradeable":true},{"id":"bath_tapware","name":"Tapware","volos_description":"Chrome basin mixer & shower set","messina_description":"Chrome basin mixer & rail shower set","portobello_description":"Matte black basin mixer, overhead rain shower & rail shower set","is_upgradeable":true},{"id":"shower_screen","name":"Shower Screen","volos_description":"Framed pivot shower screen","messina_description":"Semi-frameless shower screen","portobello_description":"Frameless glass shower screen","is_upgradeable":true},{"id":"mirror","name":"Mirror","volos_description":"Standard mirror above vanity","messina_description":"Polished edge mirror above vanity","portobello_description":"Frameless pencil edge mirror with LED backlight","is_upgradeable":true},{"id":"toilet","name":"Toilet Suite","volos_description":"Close-coupled toilet suite","messina_description":"Back-to-wall toilet suite with soft close seat","portobello_description":"Wall-faced toilet suite with concealed cistern & soft close seat","is_upgradeable":true},{"id":"bath_accessories","name":"Accessories","volos_description":"Chrome towel rail & toilet roll holder","messina_description":"Chrome towel rail, robe hook & toilet roll holder","portobello_description":"Matte black towel rail, robe hook, toilet roll holder & shelf","is_upgradeable":true}]'),
('flooring', 'Flooring', 'square.grid.3x3.fill', 6,
 '[{"id":"main_flooring","name":"Main Living Flooring","volos_description":"Vinyl plank flooring to living areas","messina_description":"Hybrid vinyl plank flooring to living areas from standard range","portobello_description":"Premium hybrid flooring to living areas from extended range","is_upgradeable":true},{"id":"carpet","name":"Carpet","volos_description":"Solution-dyed nylon carpet to bedrooms","messina_description":"Premium solution-dyed nylon carpet with upgraded underlay","portobello_description":"Luxury plush carpet with premium underlay to all bedrooms","is_upgradeable":true},{"id":"wet_area_tiles","name":"Wet Area Tiles","volos_description":"Standard ceramic tiles to wet areas","messina_description":"Porcelain tiles from standard range to wet areas","portobello_description":"Premium porcelain tiles from extended range to all wet areas","is_upgradeable":true}]'),
('internal', 'Internal Finishes', 'paintbrush.fill', 7,
 '[{"id":"int_doors","name":"Internal Doors","volos_description":"2,040mm flat panel internal doors","messina_description":"2,100mm designer deco panel internal doors","portobello_description":"2,340mm designer deco panel internal doors with premium hardware","is_upgradeable":true},{"id":"door_hardware","name":"Door Hardware","volos_description":"Standard satin chrome lever handles","messina_description":"Satin chrome lever handles with privacy locks to WC","portobello_description":"Matte black lever handles with privacy locks to WC & ensuite","is_upgradeable":true},{"id":"paint","name":"Internal Paint","volos_description":"Taubmans low sheen paint, single colour throughout","messina_description":"Taubmans low sheen paint with feature wall colour","portobello_description":"Dulux Wash & Wear low sheen paint with feature wall colours","is_upgradeable":true},{"id":"blinds","name":"Window Furnishings","volos_description":"Single roller blinds to bedrooms & living","messina_description":"Deluxe single blockout roller blinds to all windows","portobello_description":"Deluxe dual roller blinds (blockout + sunscreen) to all windows","is_upgradeable":true},{"id":"skirting","name":"Skirting & Architraves","volos_description":"67mm skirting & 42mm architraves","messina_description":"90mm skirting & 67mm architraves","portobello_description":"115mm skirting & 90mm architraves","is_upgradeable":true}]'),
('electrical', 'Electrical & Lighting', 'lightbulb.fill', 8,
 '[{"id":"powerpoints","name":"Powerpoints","volos_description":"1 double powerpoint per room","messina_description":"Double powerpoints per room, USB-A & USB-C in kitchen & main bed","portobello_description":"Multiple double powerpoints per room, USB-A & USB-C in kitchen, main bed & living","is_upgradeable":true},{"id":"switches","name":"Light Switches","volos_description":"Standard white switches & plates","messina_description":"Clipsal white Saturn switches","portobello_description":"Clipsal Iconic matte black switches & plates","is_upgradeable":true},{"id":"lighting","name":"Lighting","volos_description":"Standard LED downlights throughout","messina_description":"LED downlights with dimmer to living areas","portobello_description":"Premium LED downlights with dimmers, pendant provision & LED strip to kitchen","is_upgradeable":true},{"id":"ext_lighting","name":"External Lighting","volos_description":"1 x external light to front entry","messina_description":"External lights to front entry & alfresco","portobello_description":"External lights to front entry, alfresco & garage with sensor","is_upgradeable":true},{"id":"data_comms","name":"Data & Communications","volos_description":"NBN/Opticomm provision to 1 location","messina_description":"NBN/Opticomm provision with data points to living & main bed","portobello_description":"NBN/Opticomm provision with data points to living, main bed & study","is_upgradeable":true}]'),
('outdoor', 'Outdoor & Landscaping', 'leaf.fill', 9,
 '[{"id":"alfresco","name":"Alfresco","volos_description":"Covered concrete alfresco (as per plan)","messina_description":"Covered concrete alfresco with ceiling fan provision","portobello_description":"Covered tiled alfresco with ceiling fan & gas bayonet","is_upgradeable":true},{"id":"letterbox","name":"Letterbox","volos_description":"Standard rendered letterbox","messina_description":"Rendered letterbox to match facade","portobello_description":"Premium rendered letterbox with house number","is_upgradeable":true},{"id":"clothesline","name":"Clothesline","volos_description":"Fold-down clothesline","messina_description":"Fold-down clothesline","portobello_description":"Retractable clothesline","is_upgradeable":false},{"id":"ext_tap","name":"External Taps","volos_description":"1 x garden tap","messina_description":"2 x garden taps (front & rear)","portobello_description":"2 x garden taps (front & rear) with hose connections","is_upgradeable":true}]')
ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order, items=EXCLUDED.items, updated_at=now();

-- ============================================================
-- SEED DATA — Spec Range Tiers
-- ============================================================

INSERT INTO spec_range_tiers (tier, hero_image_url, summary, highlights, room_images) VALUES
('volos',
 'https://pub-e001eb4506b145aa938b5d3badbff6a5.r2.dev/attachments/2m8uxjn7nelckolf349xo.jpg',
 'Everything you need to move into a beautifully finished home. The Volos range delivers quality fixtures, fittings and finishes that meet the high standards AVIA is known for. Designed for smart living, Volos provides a solid foundation of premium essentials without compromising on style or durability.',
 '[{"icon":"countertop.fill","title":"Laminate Benchtops","subtitle":"Quality laminate kitchen benchtops from our standard range"},{"icon":"square.stack.3d.up.fill","title":"Vinyl Plank Flooring","subtitle":"Durable vinyl plank flooring to all living areas"},{"icon":"oven.fill","title":"600mm Appliance Suite","subtitle":"600mm oven, ceramic cooktop & rangehood included"},{"icon":"ruler.fill","title":"2,440mm Ceilings","subtitle":"Standard ceiling height throughout the home"},{"icon":"window.vertical.open","title":"Aluminium Windows","subtitle":"Aluminium windows with keyed locks as standard"},{"icon":"lightbulb.fill","title":"LED Downlights","subtitle":"Standard LED downlights throughout the home"}]',
 '[{"name":"Kitchen","image_url":"https://pub-e001eb4506b145aa938b5d3badbff6a5.r2.dev/attachments/2m8uxjn7nelckolf349xo.jpg"},{"name":"Living Room","image_url":"https://pub-e001eb4506b145aa938b5d3badbff6a5.r2.dev/attachments/sxfdai5efw1uz7s7qqgmo.jpeg"},{"name":"Bathroom","image_url":"https://pub-e001eb4506b145aa938b5d3badbff6a5.r2.dev/attachments/mddj1kprc8nfc5ujxb9sc.jpeg"},{"name":"Bedroom","image_url":"https://pub-e001eb4506b145aa938b5d3badbff6a5.r2.dev/attachments/tfj102uo1tuzrdd0hlm6b.jpeg"},{"name":"Alfresco","image_url":"https://pub-e001eb4506b145aa938b5d3badbff6a5.r2.dev/attachments/t8j7r8vibjqzvubxzcnbg.jpeg"}]'),
('messina',
 'https://pub-e001eb4506b145aa938b5d3badbff6a5.r2.dev/attachments/sxfdai5efw1uz7s7qqgmo.jpeg',
 'Step up to stone benchtops, upgraded tapware and enhanced finishes throughout. The Messina range is our most popular specification, offering the perfect balance of luxury and value. Every detail has been carefully curated to elevate your everyday living experience.',
 '[{"icon":"countertop.fill","title":"20mm Stone Benchtops","subtitle":"Beautiful stone kitchen benchtops from our standard range"},{"icon":"flame.fill","title":"900mm Gas Cooktop","subtitle":"900mm oven with 5-burner gas cooktop & rangehood"},{"icon":"square.stack.3d.up.fill","title":"Hybrid Vinyl Plank","subtitle":"Premium hybrid vinyl plank flooring to living areas"},{"icon":"cabinet.fill","title":"Two-Tone Cabinetry","subtitle":"Soft-close two-tone cabinetry throughout the kitchen"},{"icon":"shower.fill","title":"Semi-Frameless Showers","subtitle":"Semi-frameless shower screens in all wet areas"},{"icon":"ruler.fill","title":"2,590mm Ceilings","subtitle":"Higher ceilings for a more spacious feel"}]',
 '[{"name":"Kitchen","image_url":"https://pub-e001eb4506b145aa938b5d3badbff6a5.r2.dev/attachments/sxfdai5efw1uz7s7qqgmo.jpeg"},{"name":"Living Room","image_url":"https://pub-e001eb4506b145aa938b5d3badbff6a5.r2.dev/attachments/j4n8xaj2jlxo0wjxvkhr8.jpeg"},{"name":"Bathroom","image_url":"https://pub-e001eb4506b145aa938b5d3badbff6a5.r2.dev/attachments/tfj102uo1tuzrdd0hlm6b.jpeg"},{"name":"Bedroom","image_url":"https://pub-e001eb4506b145aa938b5d3badbff6a5.r2.dev/attachments/t8j7r8vibjqzvubxzcnbg.jpeg"},{"name":"Alfresco","image_url":"https://pub-e001eb4506b145aa938b5d3badbff6a5.r2.dev/attachments/mddj1kprc8nfc5ujxb9sc.jpeg"}]'),
('portobello',
 'https://pub-e001eb4506b145aa938b5d3badbff6a5.r2.dev/attachments/j4n8xaj2jlxo0wjxvkhr8.jpeg',
 'The ultimate in home finishes. The Portobello range features designer selections, high-end materials and bespoke details that transform your home into a true showpiece. From premium stone benchtops to matte black fixtures and frameless glass, every element has been chosen to create an unforgettable living experience.',
 '[{"icon":"countertop.fill","title":"Premium Stone Benchtops","subtitle":"20mm premium stone benchtops from our extended range"},{"icon":"flame.fill","title":"Pyrolytic Oven & Induction","subtitle":"900mm pyrolytic oven, induction cooktop, integrated rangehood & dishwasher"},{"icon":"drop.fill","title":"Matte Black Fixtures","subtitle":"Designer matte black tapware & fixtures throughout"},{"icon":"rectangle.portrait.fill","title":"Frameless Glass Showers","subtitle":"Premium frameless glass shower screens"},{"icon":"square.stack.3d.up.fill","title":"Premium Hybrid Flooring","subtitle":"Luxury hybrid flooring from extended range"},{"icon":"ruler.fill","title":"2,740mm Ceilings","subtitle":"Extra-high ceilings for grand proportions"}]',
 '[{"name":"Kitchen","image_url":"https://pub-e001eb4506b145aa938b5d3badbff6a5.r2.dev/attachments/j4n8xaj2jlxo0wjxvkhr8.jpeg"},{"name":"Living Room","image_url":"https://pub-e001eb4506b145aa938b5d3badbff6a5.r2.dev/attachments/tfj102uo1tuzrdd0hlm6b.jpeg"},{"name":"Bathroom","image_url":"https://pub-e001eb4506b145aa938b5d3badbff6a5.r2.dev/attachments/mddj1kprc8nfc5ujxb9sc.jpeg"},{"name":"Bedroom","image_url":"https://pub-e001eb4506b145aa938b5d3badbff6a5.r2.dev/attachments/2m8uxjn7nelckolf349xo.jpg"},{"name":"Alfresco","image_url":"https://pub-e001eb4506b145aa938b5d3badbff6a5.r2.dev/attachments/t8j7r8vibjqzvubxzcnbg.jpeg"}]')
ON CONFLICT (tier) DO UPDATE SET hero_image_url=EXCLUDED.hero_image_url, summary=EXCLUDED.summary, highlights=EXCLUDED.highlights, room_images=EXCLUDED.room_images, updated_at=now();

-- ============================================================
-- SEED DATA — HomeFast Schemes
-- ============================================================

INSERT INTO homefast_schemes (id, name, subtitle, preview_colors, selections, room_images, sort_order) VALUES
('hf1', 'Coastal Breeze', 'Light and airy with soft sandy tones',
 '["E4E2D5","F9FBF1","CABFA4","C4B89C","B8A88A"]',
 '{"roof":{"option_id":"r1","option_name":"Surfmist","hex_color":"E4E2D5"},"fascia":{"option_id":"f1","option_name":"Dover White","hex_color":"F9FBF1"},"windows":{"option_id":"w1","option_name":"Surfmist","hex_color":"E4E2D5"},"garage":{"option_id":"g1","option_name":"Surfmist","hex_color":"E4E2D5"},"render":{"option_id":"re1","option_name":"Surfmist","hex_color":"E4E2D5"},"cladding":{"option_id":"cl1","option_name":"Surfmist","hex_color":"E4E2D5"},"bricks":{"option_id":"b4","option_name":"Sand","hex_color":"C4B89C"},"frontdoor":{"option_id":"fd1","option_name":"Surfmist","hex_color":"E4E2D5"},"timberposts":{"option_id":"tp1","option_name":"Surfmist","hex_color":"E4E2D5"},"alfrescotiles":{"option_id":"at3","option_name":"Sandstone","hex_color":"C4B89C"},"aggregate":{"option_id":"ea1","option_name":"Cream","hex_color":"D8D0B8"},"paint":{"option_id":"p4","option_name":"Natural White","hex_color":"E8E3D8"},"flooring":{"option_id":"fl1","option_name":"Coastal Oak","hex_color":"B8A88A"},"carpet":{"option_id":"c2","option_name":"Sandstone","hex_color":"C4B89C"},"blinds":{"option_id":"bl2","option_name":"Ivory","hex_color":"E8E0D0"},"benchtops":{"option_id":"st1","option_name":"Calacatta White","hex_color":"F0EDE8"},"splashback":{"option_id":"sp1","option_name":"White Gloss","hex_color":"F5F5F0"},"cabinetry":{"option_id":"k1","option_name":"Classic White","hex_color":"F5F5F0"},"pendants":{"option_id":"pl4","option_name":"Brushed Chrome","hex_color":"C8C8C8"},"tapware":{"option_id":"t1","option_name":"Chrome","hex_color":"C8C8C8"},"bathtiles":{"option_id":"bt2","option_name":"White Gloss","hex_color":"F5F5F0"},"vanity":{"option_id":"v1","option_name":"Classic White","hex_color":"F5F5F0"},"wardrobes":{"option_id":"ws1","option_name":"Classic White","hex_color":"F5F5F0"},"doorhandles":{"option_id":"dh1","option_name":"Satin Chrome","hex_color":"C0C0C0"},"bathaccessories":{"option_id":"ba1","option_name":"Chrome","hex_color":"C8C8C8"},"showerscreens":{"option_id":"ss1","option_name":"Silver / Chrome","hex_color":"C0C0C0"},"mirrors":{"option_id":"mi1","option_name":"Frameless Polished Edge","hex_color":"D8E0E8"},"powerpoints":{"option_id":"pp1","option_name":"Gloss White","hex_color":"F5F5F0"},"laundrytub":{"option_id":"lt1","option_name":"Classic White Cabinet","hex_color":"F5F5F0"}}',
 '[{"room":"exterior","label":"Exterior","asset_name":"scheme_coastal_exterior"},{"room":"kitchen","label":"Kitchen","asset_name":"scheme_coastal_kitchen"},{"room":"living","label":"Living Room","asset_name":"scheme_coastal_living"},{"room":"bathroom","label":"Bathroom","asset_name":"scheme_coastal_bathroom"},{"room":"bedroom","label":"Bedroom","asset_name":"scheme_coastal_bedroom"}]',
 1),
('hf2', 'Modern Charcoal', 'Bold and contemporary with dark accents',
 '["888B8A","2D2C2C","4C4F48","3A3A3A","A09A90"]',
 '{"roof":{"option_id":"r6","option_name":"Windspray","hex_color":"888B8A"},"fascia":{"option_id":"f8","option_name":"Windspray","hex_color":"888B8A"},"windows":{"option_id":"w2","option_name":"Monument","hex_color":"2D2C2C"},"garage":{"option_id":"g6","option_name":"Monument","hex_color":"2D2C2C"},"render":{"option_id":"re4","option_name":"Shale Grey","hex_color":"BDBFBA"},"cladding":{"option_id":"cl2","option_name":"Monument","hex_color":"2D2C2C"},"bricks":{"option_id":"b1","option_name":"Graphite","hex_color":"3A3A3A"},"frontdoor":{"option_id":"fd2","option_name":"Monument","hex_color":"2D2C2C"},"timberposts":{"option_id":"tp2","option_name":"Monument","hex_color":"2D2C2C"},"alfrescotiles":{"option_id":"at2","option_name":"Charcoal","hex_color":"4E4E4E"},"aggregate":{"option_id":"ea3","option_name":"Charcoal","hex_color":"4E4E4E"},"paint":{"option_id":"p1","option_name":"Vivid White","hex_color":"F7F7F2"},"flooring":{"option_id":"fl4","option_name":"Grey Wash Oak","hex_color":"A09A90"},"carpet":{"option_id":"c4","option_name":"Steel","hex_color":"8E8A84"},"blinds":{"option_id":"bl5","option_name":"Charcoal","hex_color":"4E4E4E"},"benchtops":{"option_id":"st3","option_name":"Concrete Grey","hex_color":"A8A4A0"},"splashback":{"option_id":"sp4","option_name":"Grey Stone","hex_color":"B0ACA6"},"cabinetry":{"option_id":"k4","option_name":"Ash Grey","hex_color":"A09A90"},"pendants":{"option_id":"pl2","option_name":"Matte Black","hex_color":"1A1A1A"},"tapware":{"option_id":"t3","option_name":"Matte Black","hex_color":"1A1A1A"},"bathtiles":{"option_id":"bt3","option_name":"Grey Matt","hex_color":"B0ACA6"},"vanity":{"option_id":"v3","option_name":"Coastal Grey","hex_color":"B0ACA6"},"wardrobes":{"option_id":"ws3","option_name":"Grey","hex_color":"B0ACA6"},"doorhandles":{"option_id":"dh2","option_name":"Matte Black","hex_color":"1A1A1A"},"bathaccessories":{"option_id":"ba2","option_name":"Matte Black","hex_color":"1A1A1A"},"showerscreens":{"option_id":"ss2","option_name":"Matte Black","hex_color":"1A1A1A"},"mirrors":{"option_id":"mi2","option_name":"Matte Black Frame","hex_color":"1A1A1A"},"powerpoints":{"option_id":"pp2","option_name":"Matt White","hex_color":"EEEEEA"},"laundrytub":{"option_id":"lt3","option_name":"Stone Grey Cabinet","hex_color":"B0ACA6"}}',
 '[{"room":"exterior","label":"Exterior","asset_name":"scheme_charcoal_exterior"},{"room":"kitchen","label":"Kitchen","asset_name":"scheme_charcoal_kitchen"},{"room":"living","label":"Living Room","asset_name":"scheme_charcoal_living"},{"room":"bathroom","label":"Bathroom","asset_name":"scheme_charcoal_bathroom"},{"room":"bedroom","label":"Bedroom","asset_name":"scheme_charcoal_bedroom"}]',
 2),
('hf3', 'Warm Earth', 'Natural warmth with earthy brick and timber',
 '["CABFA4","B1ADA3","9C8468","C4AA82","8B7355"]',
 '{"roof":{"option_id":"r9","option_name":"Paperbark","hex_color":"CABFA4"},"fascia":{"option_id":"f6","option_name":"Paperbark","hex_color":"CABFA4"},"windows":{"option_id":"w4","option_name":"Paperbark","hex_color":"CABFA4"},"garage":{"option_id":"g8","option_name":"Paperbark","hex_color":"CABFA4"},"render":{"option_id":"re7","option_name":"Paperbark","hex_color":"CABFA4"},"cladding":{"option_id":"cl4","option_name":"Dune","hex_color":"B1ADA3"},"bricks":{"option_id":"b6","option_name":"Hazelnut","hex_color":"9C8468"},"frontdoor":{"option_id":"fd3","option_name":"Dune","hex_color":"B1ADA3"},"timberposts":{"option_id":"tp5","option_name":"Paperbark","hex_color":"CABFA4"},"alfrescotiles":{"option_id":"at3","option_name":"Sandstone","hex_color":"C4B89C"},"aggregate":{"option_id":"ea2","option_name":"Mocha","hex_color":"8B7355"},"paint":{"option_id":"p5","option_name":"Warm White","hex_color":"F0E8DA"},"flooring":{"option_id":"fl2","option_name":"Spotted Gum","hex_color":"8B7355"},"carpet":{"option_id":"c6","option_name":"Suede","hex_color":"B0A08C"},"blinds":{"option_id":"bl3","option_name":"Linen","hex_color":"D8D0C0"},"benchtops":{"option_id":"st6","option_name":"Alpine Mist","hex_color":"D8D4CC"},"splashback":{"option_id":"sp5","option_name":"Warm Beige","hex_color":"D4C8B4"},"cabinetry":{"option_id":"k3","option_name":"Natural Oak","hex_color":"C4AA82"},"pendants":{"option_id":"pl3","option_name":"Brushed Nickel","hex_color":"B0A898"},"tapware":{"option_id":"t2","option_name":"Brushed Nickel","hex_color":"B0A898"},"bathtiles":{"option_id":"bt4","option_name":"Warm Beige","hex_color":"D4C8B4"},"vanity":{"option_id":"v2","option_name":"Natural Oak","hex_color":"C4AA82"},"wardrobes":{"option_id":"ws2","option_name":"Natural Oak","hex_color":"C4AA82"},"doorhandles":{"option_id":"dh3","option_name":"Brushed Nickel","hex_color":"B0A898"},"bathaccessories":{"option_id":"ba3","option_name":"Brushed Nickel","hex_color":"B0A898"},"showerscreens":{"option_id":"ss3","option_name":"Brushed Nickel","hex_color":"B0A898"},"mirrors":{"option_id":"mi3","option_name":"Brushed Nickel Frame","hex_color":"B0A898"},"powerpoints":{"option_id":"pp1","option_name":"Gloss White","hex_color":"F5F5F0"},"laundrytub":{"option_id":"lt2","option_name":"Natural Oak Cabinet","hex_color":"C4AA82"}}',
 '[{"room":"exterior","label":"Exterior","asset_name":"scheme_earth_exterior"},{"room":"kitchen","label":"Kitchen","asset_name":"scheme_earth_kitchen"},{"room":"living","label":"Living Room","asset_name":"scheme_earth_living"},{"room":"bathroom","label":"Bathroom","asset_name":"scheme_earth_bathroom"},{"room":"bedroom","label":"Bedroom","asset_name":"scheme_earth_bedroom"}]',
 3),
('hf4', 'Classic Neutral', 'Timeless greys with understated elegance',
 '["BDBFBA","D2D1CB","A8A8A8","B0ACA6","B8B4AE"]',
 '{"roof":{"option_id":"r5","option_name":"Shale Grey","hex_color":"BDBFBA"},"fascia":{"option_id":"f3","option_name":"Shale Grey","hex_color":"BDBFBA"},"windows":{"option_id":"w1","option_name":"Surfmist","hex_color":"E4E2D5"},"garage":{"option_id":"g3","option_name":"Shale Grey","hex_color":"BDBFBA"},"render":{"option_id":"re3","option_name":"Southerly","hex_color":"D2D1CB"},"cladding":{"option_id":"cl3","option_name":"Shale Grey","hex_color":"BDBFBA"},"bricks":{"option_id":"b3","option_name":"Silver","hex_color":"A8A8A8"},"frontdoor":{"option_id":"fd4","option_name":"Shale Grey","hex_color":"BDBFBA"},"timberposts":{"option_id":"tp3","option_name":"Shale Grey","hex_color":"BDBFBA"},"alfrescotiles":{"option_id":"at1","option_name":"Concrete Grey","hex_color":"A8A4A0"},"aggregate":{"option_id":"ea5","option_name":"Platinum","hex_color":"A8A8A8"},"paint":{"option_id":"p2","option_name":"Lexicon Quarter","hex_color":"F2F2EA"},"flooring":{"option_id":"fl4","option_name":"Grey Wash Oak","hex_color":"A09A90"},"carpet":{"option_id":"c3","option_name":"Silver","hex_color":"B8B4AE"},"blinds":{"option_id":"bl1","option_name":"White","hex_color":"F5F5F0"},"benchtops":{"option_id":"st5","option_name":"Noble Grey","hex_color":"B0ACA6"},"splashback":{"option_id":"sp2","option_name":"White Matt","hex_color":"F0F0EA"},"cabinetry":{"option_id":"k2","option_name":"Coastal Grey","hex_color":"B0ACA6"},"pendants":{"option_id":"pl1","option_name":"White","hex_color":"F5F5F0"},"tapware":{"option_id":"t1","option_name":"Chrome","hex_color":"C8C8C8"},"bathtiles":{"option_id":"bt1","option_name":"White Matt","hex_color":"F0F0EA"},"vanity":{"option_id":"v1","option_name":"Classic White","hex_color":"F5F5F0"},"wardrobes":{"option_id":"ws1","option_name":"Classic White","hex_color":"F5F5F0"},"doorhandles":{"option_id":"dh1","option_name":"Satin Chrome","hex_color":"C0C0C0"},"bathaccessories":{"option_id":"ba1","option_name":"Chrome","hex_color":"C8C8C8"},"showerscreens":{"option_id":"ss1","option_name":"Silver / Chrome","hex_color":"C0C0C0"},"mirrors":{"option_id":"mi1","option_name":"Frameless Polished Edge","hex_color":"D8E0E8"},"powerpoints":{"option_id":"pp2","option_name":"Matt White","hex_color":"EEEEEA"},"laundrytub":{"option_id":"lt1","option_name":"Classic White Cabinet","hex_color":"F5F5F0"}}',
 '[{"room":"exterior","label":"Exterior","asset_name":"scheme_neutral_exterior"},{"room":"kitchen","label":"Kitchen","asset_name":"scheme_neutral_kitchen"},{"room":"living","label":"Living Room","asset_name":"scheme_neutral_living"},{"room":"bathroom","label":"Bathroom","asset_name":"scheme_neutral_bathroom"},{"room":"bedroom","label":"Bedroom","asset_name":"scheme_neutral_bedroom"}]',
 4),
('hf5', 'Dune & Stone', 'Warm mid-tones with stone and timber',
 '["B1ADA3","C5C2AA","C8C0B0","B8B0A4","C4AA82"]',
 '{"roof":{"option_id":"r7","option_name":"Dune","hex_color":"B1ADA3"},"fascia":{"option_id":"f4","option_name":"Dune","hex_color":"B1ADA3"},"windows":{"option_id":"w6","option_name":"Windspray","hex_color":"888B8A"},"garage":{"option_id":"g4","option_name":"Dune","hex_color":"B1ADA3"},"render":{"option_id":"re6","option_name":"Evening Haze","hex_color":"C5C2AA"},"cladding":{"option_id":"cl8","option_name":"Evening Haze","hex_color":"C5C2AA"},"bricks":{"option_id":"b8","option_name":"Limestone","hex_color":"C8C0B0"},"frontdoor":{"option_id":"fd6","option_name":"Windspray","hex_color":"888B8A"},"timberposts":{"option_id":"tp4","option_name":"Dune","hex_color":"B1ADA3"},"alfrescotiles":{"option_id":"at6","option_name":"Taupe","hex_color":"B0A898"},"aggregate":{"option_id":"ea4","option_name":"Sandstone","hex_color":"C4B89C"},"paint":{"option_id":"p6","option_name":"Antique White USA","hex_color":"F0EADC"},"flooring":{"option_id":"fl5","option_name":"Classic Oak","hex_color":"B0956E"},"carpet":{"option_id":"c7","option_name":"Pebble","hex_color":"C0B8AC"},"blinds":{"option_id":"bl4","option_name":"Stone","hex_color":"B8B0A4"},"benchtops":{"option_id":"st2","option_name":"Statuario","hex_color":"E8E4DE"},"splashback":{"option_id":"sp3","option_name":"Marble Look","hex_color":"E8E4DE"},"cabinetry":{"option_id":"k5","option_name":"Stone","hex_color":"B8B0A4"},"pendants":{"option_id":"pl3","option_name":"Brushed Nickel","hex_color":"B0A898"},"tapware":{"option_id":"t2","option_name":"Brushed Nickel","hex_color":"B0A898"},"bathtiles":{"option_id":"bt5","option_name":"Ivory","hex_color":"E8E0D0"},"vanity":{"option_id":"v4","option_name":"Stone","hex_color":"B8B0A4"},"wardrobes":{"option_id":"ws2","option_name":"Natural Oak","hex_color":"C4AA82"},"doorhandles":{"option_id":"dh3","option_name":"Brushed Nickel","hex_color":"B0A898"},"bathaccessories":{"option_id":"ba3","option_name":"Brushed Nickel","hex_color":"B0A898"},"showerscreens":{"option_id":"ss3","option_name":"Brushed Nickel","hex_color":"B0A898"},"mirrors":{"option_id":"mi3","option_name":"Brushed Nickel Frame","hex_color":"B0A898"},"powerpoints":{"option_id":"pp1","option_name":"Gloss White","hex_color":"F5F5F0"},"laundrytub":{"option_id":"lt2","option_name":"Natural Oak Cabinet","hex_color":"C4AA82"}}',
 '[{"room":"exterior","label":"Exterior","asset_name":"scheme_dune_exterior"},{"room":"kitchen","label":"Kitchen","asset_name":"scheme_dune_kitchen"},{"room":"living","label":"Living Room","asset_name":"scheme_dune_living"},{"room":"bathroom","label":"Bathroom","asset_name":"scheme_dune_bathroom"},{"room":"bedroom","label":"Bedroom","asset_name":"scheme_dune_bedroom"}]',
 5),
('hf6', 'Woodland Dark', 'Sophisticated dark palette with rich contrast',
 '["4C4F48","969799","4A4946","7A6A56","4E4E4E"]',
 '{"roof":{"option_id":"r8","option_name":"Bluegum","hex_color":"969799"},"fascia":{"option_id":"f5","option_name":"Bluegum","hex_color":"969799"},"windows":{"option_id":"w5","option_name":"Woodland Grey","hex_color":"4C4F48"},"garage":{"option_id":"g7","option_name":"Woodland Grey","hex_color":"4C4F48"},"render":{"option_id":"re8","option_name":"Windspray","hex_color":"888B8A"},"cladding":{"option_id":"cl6","option_name":"Woodland Grey","hex_color":"4C4F48"},"bricks":{"option_id":"b2","option_name":"Charcoal","hex_color":"4E4E4E"},"frontdoor":{"option_id":"fd5","option_name":"Woodland Grey","hex_color":"4C4F48"},"timberposts":{"option_id":"tp6","option_name":"Woodland Grey","hex_color":"4C4F48"},"alfrescotiles":{"option_id":"at5","option_name":"Slate","hex_color":"6B6B6B"},"aggregate":{"option_id":"ea6","option_name":"Salt & Pepper","hex_color":"908C84"},"paint":{"option_id":"p3","option_name":"Lexicon Half","hex_color":"EEEEE6"},"flooring":{"option_id":"fl6","option_name":"Smoked Oak","hex_color":"7A6A56"},"carpet":{"option_id":"c8","option_name":"Truffle","hex_color":"7A7068"},"blinds":{"option_id":"bl6","option_name":"Pewter","hex_color":"8A8682"},"benchtops":{"option_id":"st3","option_name":"Concrete Grey","hex_color":"A8A4A0"},"splashback":{"option_id":"sp4","option_name":"Grey Stone","hex_color":"B0ACA6"},"cabinetry":{"option_id":"k4","option_name":"Ash Grey","hex_color":"A09A90"},"pendants":{"option_id":"pl2","option_name":"Matte Black","hex_color":"1A1A1A"},"tapware":{"option_id":"t3","option_name":"Matte Black","hex_color":"1A1A1A"},"bathtiles":{"option_id":"bt3","option_name":"Grey Matt","hex_color":"B0ACA6"},"vanity":{"option_id":"v3","option_name":"Coastal Grey","hex_color":"B0ACA6"},"wardrobes":{"option_id":"ws3","option_name":"Grey","hex_color":"B0ACA6"},"doorhandles":{"option_id":"dh2","option_name":"Matte Black","hex_color":"1A1A1A"},"bathaccessories":{"option_id":"ba2","option_name":"Matte Black","hex_color":"1A1A1A"},"showerscreens":{"option_id":"ss2","option_name":"Matte Black","hex_color":"1A1A1A"},"mirrors":{"option_id":"mi2","option_name":"Matte Black Frame","hex_color":"1A1A1A"},"powerpoints":{"option_id":"pp2","option_name":"Matt White","hex_color":"EEEEEA"},"laundrytub":{"option_id":"lt3","option_name":"Stone Grey Cabinet","hex_color":"B0ACA6"}}',
 '[{"room":"exterior","label":"Exterior","asset_name":"scheme_woodland_exterior"},{"room":"kitchen","label":"Kitchen","asset_name":"scheme_woodland_kitchen"},{"room":"living","label":"Living Room","asset_name":"scheme_woodland_living"},{"room":"bathroom","label":"Bathroom","asset_name":"scheme_woodland_bathroom"},{"room":"bedroom","label":"Bedroom","asset_name":"scheme_woodland_bedroom"}]',
 6)
ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, subtitle=EXCLUDED.subtitle, preview_colors=EXCLUDED.preview_colors, selections=EXCLUDED.selections, room_images=EXCLUDED.room_images, sort_order=EXCLUDED.sort_order, updated_at=now();

-- ============================================================
-- SEED DATA — Spec-to-Colour Mapping
-- ============================================================

INSERT INTO spec_to_colour_mapping (spec_item_id, colour_category_ids) VALUES
('roof', ARRAY['roof']),
('fascia_gutters', ARRAY['fascia']),
('facade', ARRAY['bricks','render']),
('cladding', ARRAY['cladding']),
('windows', ARRAY['windows']),
('front_entry', ARRAY['frontdoor']),
('garage_door', ARRAY['garage']),
('driveway', ARRAY['aggregate']),
('alfresco', ARRAY['alfrescotiles','timberposts']),
('benchtop', ARRAY['benchtops']),
('cabinetry', ARRAY['cabinetry']),
('splashback', ARRAY['splashback']),
('tapware', ARRAY['tapware']),
('bath_tapware', ARRAY['tapware']),
('floor_tiles', ARRAY['bathtiles']),
('wall_tiles', ARRAY['bathtiles']),
('vanity', ARRAY['vanity']),
('shower_screen', ARRAY['showerscreens']),
('mirror', ARRAY['mirrors']),
('bath_accessories', ARRAY['bathaccessories']),
('door_hardware', ARRAY['doorhandles']),
('main_flooring', ARRAY['flooring']),
('carpet', ARRAY['carpet']),
('paint', ARRAY['paint']),
('blinds', ARRAY['blinds']),
('powerpoints', ARRAY['powerpoints']),
('switches', ARRAY['powerpoints']),
('lighting', ARRAY['pendants']),
('sink', ARRAY['laundrytub'])
ON CONFLICT (spec_item_id) DO UPDATE SET colour_category_ids=EXCLUDED.colour_category_ids;

-- ============================================================
-- SEED DATA — Spec Item Images (base + tier-specific)
-- ============================================================

INSERT INTO spec_item_images (spec_item_id, base_image_url, tier_images) VALUES
('ceiling_height', 'https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/df7f70f0-741c-4eac-ae28-ed2a0d0f0fe8.png', '{"volos":"https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/81a4f3cd-b0a1-40eb-9251-955618b23732.png","messina":"https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/84f18f2c-fc3a-43c9-aeef-9c4742259af2.png","portobello":"https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/4b6ad168-dbfe-451c-8f29-2bc6705ca417.png"}'),
('concrete_slab', 'https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/48029987-71b0-454c-aa7a-9597b4bdb45e.png', '{"volos":"https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/eb6b809e-bf5d-408a-b8ca-1b1aad7151a6.png","messina":"https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/6e147606-bfe4-4673-a706-6aca62426605.png","portobello":"https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/289aa510-23a4-4bb6-90e0-3a08a5e92f83.png"}'),
('frame_trusses', 'https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/450cea15-451e-498c-a52a-23cda88f697f.png', '{"volos":"https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/7844f029-b9d3-47f5-82e3-24c330ce4841.png","messina":"https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/e8f5ffe3-b2eb-4a1e-8c72-1d391dddb18d.png","portobello":"https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/14658b42-27c9-4d65-b31c-dbd62b9adae9.png"}'),
('insulation', 'https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/a9072a23-cf0d-4268-b1a5-ab0e36223359.png', '{"volos":"https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/a3e25da4-b8ca-4bb9-b056-247d482f7c4f.png","messina":"https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/786e561b-dc34-4248-9bb8-0bb1da4289b5.png","portobello":"https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/f8cdf414-e0e8-416e-b658-8a62171eb879.png"}'),
('facade', 'https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/ce1a8876-9661-4a33-9027-5574b1be70dc.png', '{"volos":"https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/a03a43e4-fc00-4d03-80f0-cf0c8763c50d.png","messina":"https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/29f312ca-fa14-4a13-913a-332c38b15c72.png","portobello":"https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/d19fff20-9b8c-450c-80bd-0adb6ff99e93.png"}'),
('cladding', 'https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/7561ad2f-341f-4c28-a916-be13ebbf680e.png', '{"volos":"https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/6e0e6394-aca5-48c2-907f-e7bc9d47db16.png","messina":"https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/27922840-82c4-4533-be55-7c4220746874.png","portobello":"https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/29c96df7-5c32-4860-918f-3cd64fc06193.png"}'),
('roof', 'https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/334c00ed-5e46-4811-b980-e82eeb55f8c7.png', '{"volos":"https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/4aa56784-3aa6-403c-bba6-446909046c1c.png","messina":"https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/78d06622-5734-4b19-a107-d1ada2b80b34.png","portobello":"https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/e49446b1-2abd-49f1-8458-ef44cc88b5f8.png"}'),
('fascia_gutters', 'https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/40825f3c-00d2-4493-a990-99e90fbaef85.png', '{"volos":"https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/82692015-1579-4288-8980-756b7421342d.png","messina":"https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/8d68960f-e644-405c-b280-fbc0373f1e7b.png","portobello":"https://r2-pub.rork.com/projects/h7iamobq6vf0fkf7o6j6z/assets/ed25cef9-747f-4c7c-8821-7ab9574b59dd.png"}')
ON CONFLICT (spec_item_id) DO UPDATE SET base_image_url=EXCLUDED.base_image_url, tier_images=EXCLUDED.tier_images, updated_at=now();

-- NOTE: The full set of spec_item_images covers ~50 items. Add the remaining ones
-- from your Swift SpecItem.baseImageMapping and SpecItem.tierImageURLMapping as needed.
-- The app falls back to the hardcoded Swift data if these rows are missing.

-- ============================================================
-- Enable Realtime on catalogue tables
-- ============================================================

ALTER PUBLICATION supabase_realtime ADD TABLE colour_categories;
ALTER PUBLICATION supabase_realtime ADD TABLE spec_categories;
ALTER PUBLICATION supabase_realtime ADD TABLE spec_range_tiers;
ALTER PUBLICATION supabase_realtime ADD TABLE homefast_schemes;
